ALTER TABLE products
  ADD COLUMN IF NOT EXISTS sku VARCHAR(50) UNIQUE,
  ADD COLUMN IF NOT EXISTS short_description TEXT,
  ADD COLUMN IF NOT EXISTS tags TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS images TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS specs JSONB NOT NULL DEFAULT '{}';
